@GestionProductos_HostAddress = http://localhost:5218


###
GET {{GestionProductos_HostAddress}}/consultas/obtenerProductos/
Accept: application/json

###
GET {{GestionProductos_HostAddress}}/consultas/obtenerProductosPorId/
Accept: application/json
Content-Type: application/json
{
  "Id": 1,
  "Ascendente": true,
  "NumeroRegistros": 10
}

###
GET {{GestionProductos_HostAddress}}/consultas/obtenerProductosPorNombre/
Accept: application/json
Content-Type: application/json
{
  "Nombre": "Computadora",
  "Ascendente": true,
  "NumeroRegistros": 10
}
###
GET {{GestionProductos_HostAddress}}/consultas/obtenerProducto/1/
Accept: {{contentType}}

###
GET {{GestionProductos_HostAddress}}/consultas/validarInventario/
Accept: application/json
Content-Type: application/json
{
  "IdProducto": 1,
  "StockDisminuir": 10
}

### 
POST {{GestionProductos_HostAddress}}/comandos/agregarProducto/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Accept: application/json
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Nombre"
computadora

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Descripcion"

nueva

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Categoria"

Tecnologia

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Precio"

1500.99
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Stock"

10
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagen"; filename="laptop.jpg"
Content-Type: image/jpeg

< ./laptop.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
PUT {{GestionProductos_HostAddress}}/comandos/actualizarProducto/1/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Accept: application/json
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Nombre"
computadora

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Descripcion"

nueva

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Categoria"

Tecnologia

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Precio"

1500.99
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Stock"

10
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagen"; filename="laptop.jpg"
Content-Type: image/jpeg

< ./laptop.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
DELETE {{GestionProductos_HostAddress}}/comandos/eliminarProducto/1/
Content-Type: application/json