USE [GestionInventario]
GO
/****** Object:  Schema [INVENTARIO]    Script Date: 27/3/2025 10:26:50 ******/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'INVENTARIO')
EXEC sys.sp_executesql N'CREATE SCHEMA [INVENTARIO]'
GO
/****** Object:  Table [INVENTARIO].[PRODUCTOS]    Script Date: 27/3/2025 10:26:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[INVENTARIO].[PRODUCTOS]') AND type in (N'U'))
BEGIN
CREATE TABLE [INVENTARIO].[PRODUCTOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](200) NOT NULL,
	[CATEGORIA] [varchar](50) NOT NULL,
	[IMAGEN] [varbinary](max) NOT NULL,
	[PRECIO] [decimal](18, 2) NOT NULL,
	[STOCK] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
/****** Object:  Table [INVENTARIO].[TRANSACCIONES]    Script Date: 27/3/2025 10:26:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[INVENTARIO].[TRANSACCIONES]') AND type in (N'U'))
BEGIN
CREATE TABLE [INVENTARIO].[TRANSACCIONES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[TIPOTRANSACCION] [varchar](10) NOT NULL,
	[IDPRODUCTO] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[PRECIOUNITARIO] [decimal](18, 2) NOT NULL,
	[PRECIOTOTAL] [decimal](18, 2) NOT NULL,
	[DETALLE] [varchar](200) NOT NULL,
 CONSTRAINT [PK_TRANSACCIONES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_PRODUCTOS]    Script Date: 27/3/2025 10:26:50 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[INVENTARIO].[PRODUCTOS]') AND name = N'IX_PRODUCTOS')
CREATE NONCLUSTERED INDEX [IX_PRODUCTOS] ON [INVENTARIO].[PRODUCTOS]
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TRANSACCIONES_01]    Script Date: 27/3/2025 10:26:50 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[INVENTARIO].[TRANSACCIONES]') AND name = N'IX_TRANSACCIONES_01')
CREATE NONCLUSTERED INDEX [IX_TRANSACCIONES_01] ON [INVENTARIO].[TRANSACCIONES]
(
	[IDPRODUCTO] ASC,
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_TRANSACCIONES_02]    Script Date: 27/3/2025 10:26:50 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[INVENTARIO].[TRANSACCIONES]') AND name = N'IX_TRANSACCIONES_02')
CREATE NONCLUSTERED INDEX [IX_TRANSACCIONES_02] ON [INVENTARIO].[TRANSACCIONES]
(
	[IDPRODUCTO] ASC,
	[FECHA] ASC,
	[TIPOTRANSACCION] ASC,
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[INVENTARIO].[FK_TRANSACCIONES_PRODUCTOS]') AND parent_object_id = OBJECT_ID(N'[INVENTARIO].[TRANSACCIONES]'))
ALTER TABLE [INVENTARIO].[TRANSACCIONES]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACCIONES_PRODUCTOS] FOREIGN KEY([IDPRODUCTO])
REFERENCES [INVENTARIO].[PRODUCTOS] ([ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[INVENTARIO].[FK_TRANSACCIONES_PRODUCTOS]') AND parent_object_id = OBJECT_ID(N'[INVENTARIO].[TRANSACCIONES]'))
ALTER TABLE [INVENTARIO].[TRANSACCIONES] CHECK CONSTRAINT [FK_TRANSACCIONES_PRODUCTOS]
GO