CREATE TRIGGER [INVENTARIO].[TG_ACTUALIZARSTOCKNUEVATRANSACCION]
ON [INVENTARIO].[TRANSACCIONES]
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE p
    SET 
        p.STOCK = CASE 
            WHEN i.TIPOTRANSACCION = 'COMPRA' THEN p.STOCK + i.CANTIDAD
            WHEN i.TIPOTRANSACCION = 'VENTA' THEN p.STOCK - i.CANTIDAD
            ELSE p.STOCK
        END,
        p.PRECIO = CASE 
            WHEN i.TIPOTRANSACCION = 'COMPRA' THEN i.PRECIOUNITARIO
            ELSE p.PRECIO
        END
    FROM [INVENTARIO].[PRODUCTOS] p
    INNER JOIN inserted i ON p.ID = i.IDPRODUCTO;
END;
