@GestionTransacciones_HostAddress = http://localhost:5076

###
POST {{GestionTransacciones_HostAddress}}/consultas/obtenerTransaccionesPorIdProducto/
Accept: application/json
Content-Type: application/json
{
  "IdProducto": 1,
  "IdTransaccion": 1,
  "Ascendente": true,
  "NumeroRegistros": 10
}

###
POST {{GestionTransacciones_HostAddress}}/consultas/obtenerTransaccionesPorFiltros/
Accept: application/json
Content-Type: application/json
{
  "IdProducto": 1,
  "Fecha":"2025-03-27", 
  "TipoTransaccion": "COMPRA",
  "IdTransaccion": 1,
  "Ascendente": true,
  "NumeroRegistros": 10
}

###
POST {{GestionTransacciones_HostAddress}}/consultas/obtenerTransaccion/
Accept: application/json
Content-Type: application/json
{
  "IdTransaccion": 1
}
###
POST {{GestionTransacciones_HostAddress}}/comandos/agregarTransaccion/
Accept: application/json
Content-Type: application/json
{
  "IdProducto": 1,
  "Fecha":"2025-03-27",
  "TipoTransaccion": "COMPRA",
  "Cantidad": 15,
  "PrecioUnitario":10.00, 
  "PrecioTotal": 150.00,
  "Detalle": 1
}


###
POST {{GestionTransacciones_HostAddress}}/comandos/actualizarTransaccion/
Content-Type: application/json
{
  "IdTransaccion": 1
  "Cantidad": 15,
  "PrecioUnitario":10.00, 
  "PrecioTotal": 150.00,
  "Detalle": 1
}


###
POST {{GestionTransacciones_HostAddress}}/comandos/eliminarTransaccion/
Content-Type: application/json
{
    "IdProducto": 1
}